version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - mysqldb
  mysqldb :
    platform: linux/x86_64
    image: "mysql:5.7"
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE : articles
      MYSQL_USER: root
      MYSQL_PASSWORD :
      MYSQL_ROOT_PASSWORD:
